---

# Projects, Inventories, Inventory Sources, Labels, Credentials, Execution Environments, Job Templates, Workflow Job Templates


### LABELS ###

controller_labels:
  - name: test_1
    organization: CaC


### JOB TEMPLATES ###

controller_templates:

  - name: "[SC25] Test Play"
    description: Test template for Summit 25
    job_type: run
    inventory: Summit25
    project: test_summit_cac
    playbook: playbooks/test_1.yml
    organization: CaC
    labels:
      - test_1
